### ISSUE TITLE
What if User chooses the cell that is already used?

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [vvaalllerriaa/Semenova#7]
Will you program gracefully handle the case when User chooses the cell that's already taken?
Did not check this, maybe no changes are needed to your code.

**Comment by vvaalllerriaa** [comment]
<img width="430" alt="Знімок екрана 2024-06-01 о 22 11 09" src="https://github.com/vvaalllerriaa/Semenova/assets/165216586/c100f548-7aa2-4296-b874-8154da177981">
